# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-09 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeInfo',
            fields=[
                ('number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.CharField(blank=True, max_length=255, null=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('approval', models.CharField(blank=True, max_length=255, null=True)),
                ('cab_date', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'change_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentInfo',
            fields=[
                ('number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('opened_at', models.CharField(blank=True, max_length=255, null=True)),
                ('caller_id', models.CharField(blank=True, max_length=255, null=True)),
                ('u_business_service', models.CharField(blank=True, max_length=255, null=True)),
                ('u_item_type', models.CharField(blank=True, max_length=255, null=True)),
                ('u_service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('u_issue_type', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'incident_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UcsInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucs', models.CharField(blank=True, db_column='Ucs', max_length=255, null=True)),
                ('chassis_id', models.CharField(blank=True, db_column='chassis_ID', max_length=255, null=True)),
                ('chassis_sn', models.CharField(blank=True, db_column='chassis_SN', max_length=255, null=True)),
                ('slotid', models.CharField(blank=True, db_column='SlotId', max_length=255, null=True)),
                ('usrlbl', models.CharField(blank=True, db_column='usrLbl', max_length=255, null=True)),
                ('serial', models.CharField(db_column='Serial', max_length=255)),
                ('model', models.CharField(blank=True, db_column='Model', max_length=255, null=True)),
                ('mfgtime', models.CharField(blank=True, max_length=255, null=True)),
                ('adaptor', models.CharField(blank=True, db_column='Adaptor', max_length=255, null=True)),
                ('iom', models.CharField(blank=True, db_column='IOM', max_length=255, null=True)),
                ('cpu', models.CharField(blank=True, db_column='CPU', max_length=255, null=True)),
                ('numofcpus', models.CharField(blank=True, db_column='NumOfCpus', max_length=255, null=True)),
                ('numofcores', models.CharField(blank=True, db_column='NumOfCores', max_length=255, null=True)),
                ('availablememory', models.CharField(blank=True, db_column='AvailableMemory', max_length=255, null=True)),
                ('assignedtodn', models.CharField(blank=True, db_column='AssignedToDn', max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('uuid', models.CharField(blank=True, db_column='UUID', max_length=255, null=True)),
                ('firmware', models.CharField(blank=True, db_column='Firmware', max_length=255, null=True)),
            ],
            options={
                'db_table': 'ucs_inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VmInventory',
            fields=[
                ('hostname', models.CharField(blank=True, db_column='HostName', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('insuuid', models.CharField(db_column='InsUUID', max_length=255, primary_key=True, serialize=False)),
                ('os_family', models.CharField(blank=True, db_column='OS_Family', max_length=255, null=True)),
                ('moref', models.CharField(blank=True, db_column='MoRef', max_length=255, null=True)),
                ('numsocket', models.CharField(blank=True, db_column='NumSocket', max_length=255, null=True)),
                ('numcorespersocket', models.CharField(blank=True, db_column='NumCoresPerSocket', max_length=255, null=True)),
                ('total_core', models.CharField(blank=True, db_column='Total_Core', max_length=255, null=True)),
                ('memorymb', models.CharField(blank=True, db_column='MemoryMB', max_length=255, null=True)),
                ('vmstatus', models.CharField(blank=True, db_column='VMStatus', max_length=255, null=True)),
                ('network', models.CharField(blank=True, db_column='Network', max_length=255, null=True)),
                ('mac', models.CharField(blank=True, db_column='MAC', max_length=255, null=True)),
                ('vlan_id', models.CharField(blank=True, db_column='VLAN_ID', max_length=255, null=True)),
                ('network_adapter', models.CharField(blank=True, db_column='Network_Adapter', max_length=255, null=True)),
                ('block_productcol', models.CharField(blank=True, max_length=255, null=True)),
                ('ipaddress', models.CharField(blank=True, db_column='IpAddress', max_length=255, null=True)),
                ('vmdisk_count', models.CharField(blank=True, db_column='VMDisk_Count', max_length=255, null=True)),
                ('esxhost', models.CharField(blank=True, db_column='ESXHost', max_length=255, null=True)),
                ('clustername', models.CharField(blank=True, db_column='ClusterName', max_length=255, null=True)),
                ('element_manager', models.CharField(blank=True, db_column='Element_Manager', max_length=255, null=True)),
                ('datacenter', models.CharField(blank=True, db_column='DataCenter', max_length=255, null=True)),
                ('guestid', models.CharField(blank=True, db_column='GuestId', max_length=255, null=True)),
                ('market', models.CharField(blank=True, db_column='Market', max_length=255, null=True)),
                ('total_disk_count', models.CharField(blank=True, db_column='Total_Disk_Count', max_length=255, null=True)),
                ('folderlocation', models.CharField(blank=True, db_column='FolderLocation', max_length=255, null=True)),
                ('vmxpath', models.CharField(blank=True, db_column='VMXpath', max_length=255, null=True)),
                ('vmtools_verison', models.CharField(blank=True, db_column='VMTools_verison', max_length=255, null=True)),
                ('vmtools_status', models.CharField(blank=True, db_column='VMTools_Status', max_length=255, null=True)),
                ('os_version', models.CharField(blank=True, db_column='OS_Version', max_length=255, null=True)),
                ('vmdisk_allocatedinkb', models.CharField(blank=True, db_column='VMDisk_AllocatedInKB', max_length=255, null=True)),
                ('rdmdisk_allocatedinkb', models.CharField(blank=True, db_column='RDMDisk_AllocatedInKB', max_length=255, null=True)),
                ('total_storageallocatedingb', models.CharField(blank=True, db_column='Total_StorageAllocatedinGB', max_length=255, null=True)),
                ('total_disk_usageinkb', models.CharField(blank=True, db_column='Total_Disk_UsageInKB', max_length=255, null=True)),
                ('rdmdisk_count', models.CharField(blank=True, db_column='RDMDisk_Count', max_length=255, null=True)),
                ('hddetails', models.CharField(blank=True, db_column='HDDetails', max_length=255, null=True)),
                ('template', models.CharField(blank=True, db_column='Template', max_length=255, null=True)),
                ('rdmflag', models.CharField(blank=True, db_column='RDMFlag', max_length=255, null=True)),
                ('org', models.CharField(blank=True, db_column='Org', max_length=255, null=True)),
                ('prod_id', models.CharField(blank=True, db_column='prod_ID', max_length=255, null=True)),
                ('product', models.CharField(blank=True, db_column='Product', max_length=255, null=True)),
                ('productfound', models.CharField(blank=True, db_column='ProductFound', max_length=255, null=True)),
                ('rail_nodepath_id', models.CharField(blank=True, db_column='Rail_NodePath_ID', max_length=255, null=True)),
                ('rail_nodepath_name', models.CharField(blank=True, db_column='Rail_NodePath_Name', max_length=255, null=True)),
                ('devicetype', models.CharField(blank=True, db_column='DeviceType', max_length=255, null=True)),
                ('qb_id', models.CharField(blank=True, db_column='QB_ID', max_length=255, null=True)),
                ('dc_id', models.CharField(blank=True, db_column='DC_ID', max_length=255, null=True)),
                ('sizing', models.CharField(blank=True, db_column='Sizing', max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vm_inventory',
                'managed': False,
            },
        ),
    ]
