# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-08 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UcsFault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucs', models.CharField(blank=True, db_column='Ucs', max_length=255, null=True)),
                ('lasttransition', models.CharField(blank=True, max_length=255, null=True)),
                ('severity', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('dn', models.CharField(blank=True, max_length=255, null=True)),
                ('descr', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'ucs_fault',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VmCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdtime', models.CharField(db_column='CreatedTime', max_length=255)),
                ('username', models.CharField(db_column='UserName', max_length=255)),
                ('fullformattedmessage', models.CharField(db_column='FullFormattedMessage', max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'vm_creation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VmEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdtime', models.CharField(db_column='CreatedTime', max_length=255)),
                ('username', models.CharField(db_column='UserName', max_length=255)),
                ('fullformattedmessage', models.CharField(blank=True, db_column='FullFormattedMessage', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'vm_event',
                'managed': False,
            },
        ),
    ]
